### ISSUE TITLE
Lab01: Milestone not 100% completed

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-2008_DevOps_Foundations_Core_Principles_Practices#11]
# Module: 01
#### Step: 14

Description of issue
The instructions state that "alpha release milestone has been marked as complete" which is not the case when following the instructions as they currently are written.

In Task 1 we add another issue to the alpha milestone (Missing Wiki) and we don't make any change during the exercise to this one.
So, in the end it looks like this, the milestone is only 50% completed:

![image](https://github.com/MicrosoftLearning/AZ-2008_DevOps_Foundations_Core_Principles_Practices/assets/37703728/3f527cb7-e0b0-46d6-910a-82b74f8ce1ff)

Just change the text to:
alpha release milestone has been marked as 50% complete, as indicated by the green horizontal bar in the Milestone section of the page.

**Comment by LuizMacedo** [comment]
I'm closing the issue since it's fixed and will be published in the October 25th release update #13. Thank you @mkennten!
